web server

diff --git a/0x0B-ssh/0-use_a_private_key b/0x0B-ssh/0-use_a_private_key
--- a/0x0B-ssh/0-use_a_private_key
+++ b/0x0B-ssh/0-use_a_private_key
@@ -1,4 +1,27 @@
 #!/usr/bin/env bash
 #using ssh to connect to server
 
-ssh ubuntu -i ~/.ssh/school
+if [ $# -lt 4 ]
+then
+	echo "Usage: 0transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
+fi
+
+# assigning paramentals to variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_shh_key=$4
+
+# disabbling strict host key checking
+
+scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# checkking if the transfer was successful
+if [ $? -eq 0 ]
+then
+	echo "FILE WAS TRANSFEREDD SUCCESSFULLY"
+else
+	echo "FILE TRANSFER FAILED"
+fi
